### ISSUE TITLE
Support multi-document files

### ISSUE THREAD

**Issue by nadiamoe** [imroc/kubernetes.nvim#1]
Hey there, thanks for making this amazing plugin! I've been using it for several weeks now and I'm really happy with it.

Something I haven't managed to get working is proper schema detection for YAML files with multiple documents (separated by `---`). When I open one of those, no schema is apparently detected (or at least yamlls does not give any object-specific suggestions).

E.g. something like:
```yaml
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rally
spec:
  rules: []
---
apiVersion: v1
kind: Service
metadata:
  name: rally
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: rally
```

Is this something that can be configured, or is it not supported at the moment?

Thanks!
